![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [ ]:
# Import necessary packages
import pandas as pd
import numpy as np

# Load data
airbnb_price = pd.read_csv('./data/airbnb_price.csv')
airbnb_room_type = pd.read_excel('./data/airbnb_room_type.xlsx')
airbnb_last_review = pd.read_csv('./data/airbnb_last_review.tsv', sep='\t')

# Print the first few rows of each data frame
print(airbnb_price.head())
print(airbnb_room_type.head())
print(airbnb_last_review.head())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [65]:
# Check each data frame for nu
print(airbnb_price.isnull().sum())
print(airbnb_room_type.isnull().sum())
print(airbnb_last_review.isnull().sum())

listing_id     0
price          0
nbhood_full    0
dtype: int64
listing_id      0
description    10
room_type       0
dtype: int64
listing_id     0
host_name      8
last_review    0
dtype: int64

In [ ]:
# Fill null values in the description column
airbnb_room_type["description"] = airbnb_room_type["description"].fillna("No description")

# Fill null values in the host_name column
airbnb_last_review["host_name"] = airbnb_last_review["host_name"].fillna("No host name")

# Double check if there are no nulls
print("Null values in description column: " + str(airbnb_room_type["description"].isnull().sum()))
print("Null values in host_name column: " + str(airbnb_last_review["host_name"].isnull().sum()))

Null values in description column: 0
Null values in host_name column: 0

##### What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.

In [ ]:
# Convert the data type of last_review to datetime
airbnb_last_review["last_review"] = pd.to_datetime(airbnb_last_review["last_review"])
airbnb_last_review.head()

   listing_id    host_name last_review
0        2595     Jennifer  2019-05-21
1        3831  LisaRoxanne  2019-07-05
2        5099        Chris  2019-06-22
3        5178     Shunichi  2019-06-24
4        5238          Ben  2019-06-09

In [ ]:
# Sort the data frame by review dates
airbnb_last_review = airbnb_last_review.sort_values("last_review")
airbnb_last_review.head()

       listing_id      host_name last_review
12007    21751907  Aura Angelica  2019-01-01
10430    19708955          Karen  2019-01-01
14845    25931882            Can  2019-01-01
7203     13936825        Shlomit  2019-01-01
17123    28813184        Carolyn  2019-01-01

In [ ]:
# Retrieve the review date of the first row of data (earliest)
earliest_review_date = airbnb_last_review.iloc[0]["last_review"]
print(earliest_review_date)

# Retrieve the review date of the last row of data (latest)
latest_review_date = airbnb_last_review.iloc[-1]["last_review"]
print(latest_review_date)

2019-01-01 00:00:00
2019-07-09 00:00:00

##### How many of the listings are private rooms? Save this into any variable.

In [ ]:
# Check the different values for room type
print(airbnb_room_type["room_type"].value_counts())
print("\n")

# Convert all values to lowercase
airbnb_room_type["room_type"] = airbnb_room_type["room_type"].str.lower()

# Check if initially duplicated values are under one value
print(airbnb_room_type["room_type"].value_counts())

# Get the total number of private room type
private_room_count = (airbnb_room_type["room_type"] == "private room").sum()

# Display the results
print("No. of Private Rooms Listings: " + str(private_room_count))

room_type
Entire home/apt    8458
Private room       7241
entire home/apt    2665
private room       2248
ENTIRE HOME/APT    2143
PRIVATE ROOM       1867
Shared room         380
shared room         110
SHARED ROOM          97
Name: count, dtype: int64


room_type
entire home/apt    13266
private room       11356
shared room          587
Name: count, dtype: int64
No. of Private Rooms Listings: 11356

##### What is the average listing price? Round to the nearest two decimal places and save into a variable.

In [ ]:
# Check the format for price column values
print(airbnb_price["price"].value_counts().head())

# Retain the integer component of the column values
airbnb_price["price"] = airbnb_price["price"].str.replace(" dollars", "")

# Convert the data type to int
airbnb_price["price"] = airbnb_price["price"].astype("int")

# Double check the changes
print(airbnb_price["price"].value_counts().head())

# Compute for the average listing price
ave_listing_price = round((airbnb_price["price"].mean()),2)

# Display the result
print("Average Listing Price: " + str(ave_listing_price) + " dollars")

price
150 dollars    982
100 dollars    891
60 dollars     717
50 dollars     709
75 dollars     691
Name: count, dtype: int64
price
150    982
100    891
60     717
50     709
75     691
Name: count, dtype: int64
Average Listing Price: 141.78 dollars

##### Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.

In [ ]:
# Create a dictionary that maps the column name to its corresponding value
review_dates_dict = [{"first_reviewed":earliest_review_date, "last_reviewed": latest_review_date, "nb_private_rooms": private_room_count, "avg_price":ave_listing_price }]

# Create the data frame using the dictionary
review_dates = pd.DataFrame(review_dates_dict)

# Display the resulting data frame
review_dates

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78